SAVE_PATH = r'C:\Users\17337\houszhou\data\SpiderData\微信公众号\data\清博数据.json'
COOKIES_PATH = r'cookies.json'
SLEEP_TIME = 10
ACCOUNT = 13726542575
PASSWORD = ''

LINK_LIST = [
    {'fakeid': 'MjM5MjE5MjA0MA==', 'name': '深圳之窗', 'link': '/rank/wxdetail?wxname=cQ2BhDlSbJmqNiondgW5F2u1ZzA3NTUO0O0O',
     'wxname': 'cQ2BhDlSbJmqNiondgW5F2u1ZzA3NTUO0O0O', 'wx': 'shenchuang0755'},
    {'fakeid': 'MzAxNTg3OTUzMw==', 'name': '深圳之声', 'link': '/rank/wxdetail?wxname=cQ3BpD6ScJ3qZi2n',
     'wxname': 'cQ3BpD6ScJ3qZi2n', 'wx': 'szzsvv'},
    {'fakeid': 'MzA5MjE1NDE2Mw==', 'name': '每日深圳', 'link': '/rank/wxdetail?wxname=RQGBFDpSbJHqliznegj5g241',
     'wxname': 'RQGBFDpSbJHqliznegj5g241', 'wx': 'Dailysz88'},
    {'fakeid': 'MjM5ODUzOTY5Mg==', 'name': '搜狐焦点深圳', 'link': '/rank/wxdetail?wxname=ZQmB9DjSdJXqMitncg35o2O0O0O1',
     'wxname': 'ZQmB9DjSdJXqMitncg35o2O0O0O1', 'wx': 'focus-sz'},
    {'fakeid': 'MzIxMTEyODA2OA==', 'name': '全深圳', 'link': '/rank/wxdetail?wxname=cQ3BoD1SNJXqNi6n',
     'wxname': 'cQ3BoD1SNJXqNi6n', 'wx': 'sz55sz'},
    {'fakeid': 'MzA3NjU5MTM0NQ==', 'name': '吃喝玩乐在深圳', 'link': '/rank/wxdetail?wxname=UQ1BpDfSMJjqAixnNgQ5O0O0O2O0O0O1',
     'wxname': 'UQ1BpDfSMJjqAixnNgQ5O0O0O2O0O0O1', 'wx': 'SZ_2015'},
    {'fakeid': 'MzA5MTIyNzcwOA==', 'name': '深圳生活', 'link': '/rank/wxdetail?wxname=cQ3BpDzSaJDqkiynMgA5O0O0O2O0O0O1',
     'wxname': 'cQ3BpDzSaJDqkiynMgA5O0O0O2O0O0O1', 'wx': 'szsh920'},
    {'fakeid': 'MzA3ODEwOTk2Ng==', 'name': '深圳生活圈', 'link': '/rank/wxdetail?wxname=cQ2BhDxSMJDqci1nNgQ5O0O0O2O0O0O1',
     'wxname': 'cQ2BhDxSMJDqci1nNgQ5O0O0O2O0O0O1', 'wx': 'shq0755'},
    {'fakeid': 'MzA5NTMzODAzMQ==', 'name': '深圳微时光', 'link': '/rank/wxdetail?wxname=cQ3BpDkSYJXqlizn',
     'wxname': 'cQ3BpDkSYJXqlizn', 'wx': 'szdays'},
    {'fakeid': 'MzA5OTcxNzg4Mw==', 'name': '深圳潮人生活', 'link': '/rank/wxdetail?wxname=UQ1BpDMSaJWqZilnLgT5A231NTUO0O0O',
     'wxname': 'UQ1BpDMSaJWqZilnLgT5A231NTUO0O0O', 'wx': 'SZLife-0755'},
    {'fakeid': 'MzA4NTczOTMzMQ==', 'name': '深圳大件事', 'link': '/rank/wxdetail?wxname=bQmBFDuSZJHqViznegg5O0O0O2O0O0O1',
     'wxname': 'bQmBFDuSZJHqViznegg5O0O0O2O0O0O1', 'wx': 'nandusz'},
    {'fakeid': 'MzUzMjY3NTk0Ng==', 'name': '深圳潮事儿', 'link': '/rank/wxdetail?wxname=cQ3BpDjScJ2qViyn',
     'wxname': 'cQ3BpDjScJ2qViyn', 'wx': 'szcser'},
    {'fakeid': 'MzA4NTU2MDY1NA==', 'name': '深圳优生活', 'link': '/rank/wxdetail?wxname=cQ3BpD5ScJ2qgi4nOgD5g241',
     'wxname': 'cQ3BpD5ScJ2qgi4nOgD5g241', 'wx': 'szysh8888'},
    {'fakeid': 'MzA3NDE4MTkyOA==', 'name': '一个深圳', 'link': '/rank/wxdetail?wxname=cQ3BpDzSeJmqRi5n',
     'wxname': 'cQ3BpDzSeJmqRi5n', 'wx': 'szszdy'},
    {'fakeid': 'MzI1OTA5Mzc4Mw==', 'name': '深圳公安发布', 'link': '/rank/wxdetail?wxname=cQ3BpDnSYJWqZiin',
     'wxname': 'cQ3BpDnSYJWqZiin', 'wx': 'szgafb'},
    {'fakeid': 'MjM5MDA2MDMwMA==', 'name': '深圳发布', 'link': '/rank/wxdetail?wxname=cQ3BpD3SYJmqZiindgA5O0O0O2O0O0O1',
     'wxname': 'cQ3BpD3SYJmqZiindgA5O0O0O2O0O0O1', 'wx': 'szwbfbt'},
    {'fakeid': 'MzIyNzI1NDI4Nw==', 'name': '十分深圳', 'link': '/rank/wxdetail?wxname=dQHBpDzSaJGqViunegm5h2l1bgO0O0OO0O0O',
     'wxname': 'dQHBpDzSaJGqViunegm5h2l1bgO0O0OO0O0O', 'wx': 'tzshenzhen'},
    {'fakeid': 'MzA3NDMzNTQ4Mw==', 'name': '深圳交警权威发布', 'link': '/rank/wxdetail?wxname=cQ3BpDqSaJnqFi3nZgm5I2O0O0O1',
     'wxname': 'cQ3BpDqSaJnqFi3nZgm5I2O0O0O1', 'wx': 'szjjqwfb'},
    {'fakeid': 'MjM5NDA4NzM0MQ==', 'name': '深圳第一', 'link': '/rank/wxdetail?wxname=ZQGBlD5SaJTqAi3nNgT5U2O0O0O1',
     'wxname': 'ZQGBlD5SaJTqAi3nNgT5U2O0O0O1', 'wx': 'diyi0755'},
    {'fakeid': 'MjM5MTk5MDQ2MQ==', 'name': '深圳同城', 'link': '/rank/wxdetail?wxname=cQ3BpDxScJTqgiynMgT5U221',
     'wxname': 'cQ3BpDxScJTqgiynMgT5U221', 'wx': 'szqq82156'},
    {'fakeid': 'MzIzOTcyNDEzMg==', 'name': '深圳商报', 'link': '/rank/wxdetail?wxname=cQ3BpDlSZJDqIiwnMgT5g2O0O0O1',
     'wxname': 'cQ3BpDlSZJDqIiwnMgT5g2O0O0O1', 'wx': 'szed2018'},
    {'fakeid': 'MjM5MTAzODc2MA==', 'name': '深圳特区报', 'link': '/rank/wxdetail?wxname=cQ2BhDlSbJnqpionZgW55201ZXF1YmFv',
     'wxname': 'cQ2BhDlSbJnqpionZgW55201ZXF1YmFv', 'wx': 'shenzhentequbao'},
    {'fakeid': 'MzAxMDU2MDM3OA==', 'name': '深圳潮流圈', 'link': '/rank/wxdetail?wxname=cQ2BhD6SYJ2qxixn',
     'wxname': 'cQ2BhD6SYJ2qxixn', 'wx': 'shzclq'},
    {'fakeid': 'MzA4OTQ5NTk2Mw==', 'name': '深圳本地宝', 'link': '/rank/wxdetail?wxname=YQmBRDiScJ2qhilnbgn5p2o1ZW4O0O0O',
     'wxname': 'YQmBRDiScJ2qhilnbgn5p2o1ZW4O0O0O', 'wx': 'bdbshenzhen'},
    {'fakeid': 'MzI3MDAyMTUzOA==', 'name': '深圳全接触',
     'link': '/rank/wxdetail?wxname=cQXBVDhSbJmqpipnZgW5N2o1dTg4ODgO0O0O',
     'wxname': 'cQXBVDhSbJmqpipnZgW5N2o1dTg4ODgO0O0O', 'wx': 'quanjiechu8888'},
    {'fakeid': 'Mzg2ODEzMjA0OA==', 'name': '深圳地铁', 'link': '/rank/wxdetail?wxname=ZQ2BhDfSNJDqQiwnMgT5d2h1ODgyMmIw',
     'wxname': 'ZQ2BhDfSNJDqQiwnMgT5d2h1ODgyMmIw', 'wx': 'gh_44017a8822b0'},
    {'fakeid': 'MzA4MzA2MDg4OA==', 'name': '深圳吃喝玩乐', 'link': '/rank/wxdetail?wxname=cQ3BpDoSZJWq4ixnNgj5g2O0O0O1',
     'wxname': 'cQ3BpDoSZJWq4ixnNgj5g2O0O0O1', 'wx': 'szhen168'}
]
